// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBmgb_eDac_ES0oDo0i8UBOlQ-3TWYpCc',
    appId: '1:77039310051:web:3974d2160f52f94c2921d6',
    messagingSenderId: '77039310051',
    projectId: 'football-ground-management',
    authDomain: 'football-ground-management.firebaseapp.com',
    storageBucket: 'football-ground-management.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC3W9TgDd_0h9OnFjKsf4_Jx-HkIP_onA',
    appId: '1:77039310051:android:d09331efd8ed40502921d6',
    messagingSenderId: '77039310051',
    projectId: 'football-ground-management',
    storageBucket: 'football-ground-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPoY6pIycpVdUSxtp-KST06I1224RUyYc',
    appId: '1:77039310051:ios:34a653d61cf59b782921d6',
    messagingSenderId: '77039310051',
    projectId: 'football-ground-management',
    storageBucket: 'football-ground-management.appspot.com',
    iosClientId:
        '77039310051-qg8ak3m48671afktb186jqaudc0i9gbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.footballGroundManagement',
  );
}
